//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.29 at 07:00:00 PM EDT 
//


package scripts.ServiceScript;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ServiceDefinition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceDefinition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Variables" type="{http://www.example.org/ServiceSchema}VariablesListType"/>
 *         &lt;element name="Activities" type="{http://www.example.org/ServiceSchema}ActivityList"/>
 *         &lt;element name="Transitions" type="{http://www.example.org/ServiceSchema}TransitionList"/>
 *         &lt;element name="StartTask" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceDefinition", propOrder = {
    "name",
    "variables",
    "activities",
    "transitions",
    "startTask"
})
public class ServiceDefinition {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Variables", required = true)
    protected VariablesListType variables;
    @XmlElement(name = "Activities", required = true)
    protected ActivityList activities;
    @XmlElement(name = "Transitions", required = true)
    protected TransitionList transitions;
    @XmlElement(name = "StartTask", required = true)
    protected String startTask;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the variables property.
     * 
     * @return
     *     possible object is
     *     {@link VariablesListType }
     *     
     */
    public VariablesListType getVariables() {
        return variables;
    }

    /**
     * Sets the value of the variables property.
     * 
     * @param value
     *     allowed object is
     *     {@link VariablesListType }
     *     
     */
    public void setVariables(VariablesListType value) {
        this.variables = value;
    }

    /**
     * Gets the value of the activities property.
     * 
     * @return
     *     possible object is
     *     {@link ActivityList }
     *     
     */
    public ActivityList getActivities() {
        return activities;
    }

    /**
     * Sets the value of the activities property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActivityList }
     *     
     */
    public void setActivities(ActivityList value) {
        this.activities = value;
    }

    /**
     * Gets the value of the transitions property.
     * 
     * @return
     *     possible object is
     *     {@link TransitionList }
     *     
     */
    public TransitionList getTransitions() {
        return transitions;
    }

    /**
     * Sets the value of the transitions property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransitionList }
     *     
     */
    public void setTransitions(TransitionList value) {
        this.transitions = value;
    }

    /**
     * Gets the value of the startTask property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartTask() {
        return startTask;
    }

    /**
     * Sets the value of the startTask property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartTask(String value) {
        this.startTask = value;
    }

}
