//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.29 at 07:00:00 PM EDT 
//


package scripts.ServiceScript;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TransitionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransitionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Source" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Sink" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Guard" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransitionType", propOrder = {
    "name",
    "source",
    "sink",
    "guard"
})
public class TransitionType {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Source", required = true)
    protected String source;
    @XmlElement(name = "Sink", required = true)
    protected String sink;
    @XmlElement(name = "Guard", required = true)
    protected String guard;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSource(String value) {
        this.source = value;
    }

    /**
     * Gets the value of the sink property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSink() {
        return sink;
    }

    /**
     * Sets the value of the sink property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSink(String value) {
        this.sink = value;
    }

    /**
     * Gets the value of the guard property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuard() {
        return guard;
    }

    /**
     * Sets the value of the guard property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuard(String value) {
        this.guard = value;
    }

}
