//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.30 at 11:17:44 AM EDT 
//


package scripts.OracleScript;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the scripts.OracleScript package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Oracle_QNAME = new QName("http://www.example.org/OracleSchema", "Oracle");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: scripts.OracleScript
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OracleDefinition }
     * 
     */
    public OracleDefinition createOracleDefinition() {
        return new OracleDefinition();
    }

    /**
     * Create an instance of {@link VariableMappingsType }
     * 
     */
    public VariableMappingsType createVariableMappingsType() {
        return new VariableMappingsType();
    }

    /**
     * Create an instance of {@link VariableMappingDefinition }
     * 
     */
    public VariableMappingDefinition createVariableMappingDefinition() {
        return new VariableMappingDefinition();
    }

    /**
     * Create an instance of {@link ConstraintsType }
     * 
     */
    public ConstraintsType createConstraintsType() {
        return new ConstraintsType();
    }

    /**
     * Create an instance of {@link ConstraintDefinition }
     * 
     */
    public ConstraintDefinition createConstraintDefinition() {
        return new ConstraintDefinition();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OracleDefinition }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/OracleSchema", name = "Oracle")
    public JAXBElement<OracleDefinition> createOracle(OracleDefinition value) {
        return new JAXBElement<OracleDefinition>(_Oracle_QNAME, OracleDefinition.class, null, value);
    }

}
