//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.30 at 11:17:44 AM EDT 
//


package scripts.OracleScript;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OracleDefinition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OracleDefinition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="VariableMappings" type="{http://www.example.org/OracleSchema}VariableMappingsType"/>
 *         &lt;element name="Constraints" type="{http://www.example.org/OracleSchema}ConstraintsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OracleDefinition", propOrder = {
    "name",
    "variableMappings",
    "constraints"
})
public class OracleDefinition {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "VariableMappings", required = true)
    protected VariableMappingsType variableMappings;
    @XmlElement(name = "Constraints", required = true)
    protected ConstraintsType constraints;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the variableMappings property.
     * 
     * @return
     *     possible object is
     *     {@link VariableMappingsType }
     *     
     */
    public VariableMappingsType getVariableMappings() {
        return variableMappings;
    }

    /**
     * Sets the value of the variableMappings property.
     * 
     * @param value
     *     allowed object is
     *     {@link VariableMappingsType }
     *     
     */
    public void setVariableMappings(VariableMappingsType value) {
        this.variableMappings = value;
    }

    /**
     * Gets the value of the constraints property.
     * 
     * @return
     *     possible object is
     *     {@link ConstraintsType }
     *     
     */
    public ConstraintsType getConstraints() {
        return constraints;
    }

    /**
     * Sets the value of the constraints property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConstraintsType }
     *     
     */
    public void setConstraints(ConstraintsType value) {
        this.constraints = value;
    }

}
