//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.30 at 11:17:44 AM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/OracleSchema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package scripts.OracleScript;
