//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.29 at 07:00:41 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/ServiceChoreographySchema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package scripts.ChoreographyScript;
