//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.07 at 04:23:42 PM EDT 
//


package scripts.TestingScript;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the scripts.TestingScript package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TestingScript_QNAME = new QName("http://www.example.org/TestingScriptSchema", "TestingScript");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: scripts.TestingScript
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TestingScriptDefinition }
     * 
     */
    public TestingScriptDefinition createTestingScriptDefinition() {
        return new TestingScriptDefinition();
    }

    /**
     * Create an instance of {@link ServicesType }
     * 
     */
    public ServicesType createServicesType() {
        return new ServicesType();
    }

    /**
     * Create an instance of {@link ChoreographyType }
     * 
     */
    public ChoreographyType createChoreographyType() {
        return new ChoreographyType();
    }

    /**
     * Create an instance of {@link MutationsType }
     * 
     */
    public MutationsType createMutationsType() {
        return new MutationsType();
    }

    /**
     * Create an instance of {@link TestCaseType }
     * 
     */
    public TestCaseType createTestCaseType() {
        return new TestCaseType();
    }

    /**
     * Create an instance of {@link OracleType }
     * 
     */
    public OracleType createOracleType() {
        return new OracleType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TestingScriptDefinition }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/TestingScriptSchema", name = "TestingScript")
    public JAXBElement<TestingScriptDefinition> createTestingScript(TestingScriptDefinition value) {
        return new JAXBElement<TestingScriptDefinition>(_TestingScript_QNAME, TestingScriptDefinition.class, null, value);
    }

}
