//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.07 at 04:23:42 PM EDT 
//


package scripts.TestingScript;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TestingScriptDefinition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TestingScriptDefinition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Services" type="{http://www.example.org/TestingScriptSchema}ServicesType"/>
 *         &lt;element name="TestCase" type="{http://www.example.org/TestingScriptSchema}TestCaseType"/>
 *         &lt;element name="Choreography" type="{http://www.example.org/TestingScriptSchema}ChoreographyType"/>
 *         &lt;element name="Oracle" type="{http://www.example.org/TestingScriptSchema}OracleType"/>
 *         &lt;element name="Mutations" type="{http://www.example.org/TestingScriptSchema}MutationsType"/>
 *         &lt;element name="InconsistencyMutations" type="{http://www.example.org/TestingScriptSchema}MutationsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TestingScriptDefinition", propOrder = {
    "name",
    "services",
    "testCase",
    "choreography",
    "oracle",
    "mutations",
    "inconsistencyMutations"
})
public class TestingScriptDefinition {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Services", required = true)
    protected ServicesType services;
    @XmlElement(name = "TestCase", required = true)
    protected TestCaseType testCase;
    @XmlElement(name = "Choreography", required = true)
    protected ChoreographyType choreography;
    @XmlElement(name = "Oracle", required = true)
    protected OracleType oracle;
    @XmlElement(name = "Mutations", required = true)
    protected MutationsType mutations;
    @XmlElement(name = "InconsistencyMutations", required = true)
    protected MutationsType inconsistencyMutations;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the services property.
     * 
     * @return
     *     possible object is
     *     {@link ServicesType }
     *     
     */
    public ServicesType getServices() {
        return services;
    }

    /**
     * Sets the value of the services property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServicesType }
     *     
     */
    public void setServices(ServicesType value) {
        this.services = value;
    }

    /**
     * Gets the value of the testCase property.
     * 
     * @return
     *     possible object is
     *     {@link TestCaseType }
     *     
     */
    public TestCaseType getTestCase() {
        return testCase;
    }

    /**
     * Sets the value of the testCase property.
     * 
     * @param value
     *     allowed object is
     *     {@link TestCaseType }
     *     
     */
    public void setTestCase(TestCaseType value) {
        this.testCase = value;
    }

    /**
     * Gets the value of the choreography property.
     * 
     * @return
     *     possible object is
     *     {@link ChoreographyType }
     *     
     */
    public ChoreographyType getChoreography() {
        return choreography;
    }

    /**
     * Sets the value of the choreography property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChoreographyType }
     *     
     */
    public void setChoreography(ChoreographyType value) {
        this.choreography = value;
    }

    /**
     * Gets the value of the oracle property.
     * 
     * @return
     *     possible object is
     *     {@link OracleType }
     *     
     */
    public OracleType getOracle() {
        return oracle;
    }

    /**
     * Sets the value of the oracle property.
     * 
     * @param value
     *     allowed object is
     *     {@link OracleType }
     *     
     */
    public void setOracle(OracleType value) {
        this.oracle = value;
    }

    /**
     * Gets the value of the mutations property.
     * 
     * @return
     *     possible object is
     *     {@link MutationsType }
     *     
     */
    public MutationsType getMutations() {
        return mutations;
    }

    /**
     * Sets the value of the mutations property.
     * 
     * @param value
     *     allowed object is
     *     {@link MutationsType }
     *     
     */
    public void setMutations(MutationsType value) {
        this.mutations = value;
    }

    /**
     * Gets the value of the inconsistencyMutations property.
     * 
     * @return
     *     possible object is
     *     {@link MutationsType }
     *     
     */
    public MutationsType getInconsistencyMutations() {
        return inconsistencyMutations;
    }

    /**
     * Sets the value of the inconsistencyMutations property.
     * 
     * @param value
     *     allowed object is
     *     {@link MutationsType }
     *     
     */
    public void setInconsistencyMutations(MutationsType value) {
        this.inconsistencyMutations = value;
    }

}
